#include "loomConfig.hpp"

#include <algorithm>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <vector>

#include <ryml.hpp>
#include <ryml_std.hpp>

namespace {

std::string readFile(const std::filesystem::path &path) {
  std::ifstream f(path, std::ios::binary);
  std::ostringstream buf;
  buf << f.rdbuf();
  return buf.str();
}

std::string yamlEscape(const std::string &s) {
  std::string out = "\"";
  for (char c : s) {
    if (c == '"' || c == '\\') out += '\\';
    out += c;
  }
  out += "\"";
  return out;
}

} // namespace

std::unordered_map<std::string, DepConfig> readDepsConfig(const std::filesystem::path &loomYmlPath) {
  std::unordered_map<std::string, DepConfig> result;
  if (!std::filesystem::exists(loomYmlPath)) return result;

  std::string data = readFile(loomYmlPath);
  ryml::Tree tree = ryml::parse_in_place(ryml::to_substr(data));
  ryml::ConstNodeRef root = tree.rootref();
  if (!root.is_map() || !root.has_child("deps")) return result;

  ryml::ConstNodeRef deps = root["deps"];
  if (!deps.is_map()) return result;

  for (ryml::ConstNodeRef entry : deps.children()) {
    std::string name(entry.key().str, entry.key().len);
    DepConfig cfg;

    if (entry.is_map()) {
      if (entry.has_child("source")) {
        std::string source;
        entry["source"].load(&source);
        cfg.source = source;
      }
      if (entry.has_child("embed")) entry["embed"].load(&cfg.embed);
    } else if (entry.is_val() || entry.is_keyval()) {
      std::string source;
      entry.load(&source);
      cfg.source = source;
    }

    result[name] = cfg;
  }

  return result;
}

std::unordered_map<std::string, LockEntry> readLockFile(const std::filesystem::path &lockPath) {
  std::unordered_map<std::string, LockEntry> result;
  if (!std::filesystem::exists(lockPath)) return result;

  std::string data = readFile(lockPath);
  ryml::Tree tree = ryml::parse_in_place(ryml::to_substr(data));
  ryml::ConstNodeRef root = tree.rootref();
  if (!root.is_map() || !root.has_child("deps")) return result;

  ryml::ConstNodeRef deps = root["deps"];
  if (!deps.is_map()) return result;

  for (ryml::ConstNodeRef entry : deps.children()) {
    if (!entry.is_map()) continue;

    std::string name(entry.key().str, entry.key().len);
    LockEntry lock;
    if (entry.has_child("source")) entry["source"].load(&lock.source);
    if (entry.has_child("commit")) entry["commit"].load(&lock.commit);
    if (entry.has_child("sha256")) entry["sha256"].load(&lock.sha256);
    if (entry.has_child("contentHash")) entry["contentHash"].load(&lock.contentHash);
    result[name] = lock;
  }

  return result;
}

void writeLockFile(const std::filesystem::path &lockPath, const std::unordered_map<std::string, LockEntry> &entries) {
  std::string out = "# This file is generated by `loom install`. Do not edit by hand.\ndeps:\n";

  if (entries.empty()) {
    out += "{}\n";
  } else {
    std::vector<std::string> names;
    names.reserve(entries.size());
    for (const auto &[name, lock] : entries) names.push_back(name);
    std::sort(names.begin(), names.end());

    for (const std::string &name : names) {
      const LockEntry &lock = entries.at(name);
      out += "  " + name + ":\n";
      out += "    source: " + yamlEscape(lock.source) + "\n";
      if (!lock.commit.empty()) out += "    commit: " + yamlEscape(lock.commit) + "\n";
      if (!lock.sha256.empty()) out += "    sha256: " + yamlEscape(lock.sha256) + "\n";
      if (!lock.contentHash.empty()) out += "    contentHash: " + yamlEscape(lock.contentHash) + "\n";
    }
  }

  std::ofstream f(lockPath, std::ios::binary);
  f << out;
}

void addDepToConfig(const std::filesystem::path &loomYmlPath, const std::string &name, const std::string &source, bool embed) {
  std::string data = std::filesystem::exists(loomYmlPath) ? readFile(loomYmlPath) : std::string("{}\n");

  ryml::Tree tree = ryml::parse_in_place(ryml::to_substr(data));
  ryml::NodeRef root = tree.rootref();
  if (!root.is_map()) root.set_map();

  ryml::NodeRef deps;
  if (root.has_child("deps")) {
    deps = root["deps"];
    if (!deps.is_map()) deps.set_map();
  } else {
    deps = root.append_child();
    deps.set_key("deps");
    deps.set_map();
  }

  ryml::csubstr nameKey = ryml::to_csubstr(name);
  if (deps.has_child(nameKey)) deps.remove_child(nameKey);

  ryml::NodeRef entry = deps.append_child();
  entry.set_key(nameKey);
  entry.set_map();
  entry["source"].save(source);
  if (embed) entry["embed"].set_val("true");

  std::string out;
  ryml::emitrs_yaml(tree, &out);

  std::ofstream f(loomYmlPath, std::ios::binary);
  if (!f.is_open()) throw std::runtime_error("Failed to write " + loomYmlPath.string());
  f << out;
}

bool removeDepFromConfig(const std::filesystem::path &loomYmlPath, const std::string &name) {
  if (!std::filesystem::exists(loomYmlPath)) return false;

  std::string data = readFile(loomYmlPath);
  ryml::Tree tree = ryml::parse_in_place(ryml::to_substr(data));
  ryml::NodeRef root = tree.rootref();
  if (!root.is_map() || !root.has_child("deps")) return false;

  ryml::NodeRef deps = root["deps"];
  ryml::csubstr nameKey = ryml::to_csubstr(name);
  if (!deps.is_map() || !deps.has_child(nameKey)) return false;

  deps.remove_child(nameKey);

  std::string out;
  ryml::emitrs_yaml(tree, &out);

  std::ofstream f(loomYmlPath, std::ios::binary);
  if (!f.is_open()) throw std::runtime_error("Failed to write " + loomYmlPath.string());
  f << out;
  return true;
}
